name = "netclipboard"
main = "src/index.js"
compatibility_date = "2026-01-17"
workers_dev = false
preview_urls = false
minify = true

[[routes]]
pattern = "clip.us.ci"
custom_domain = true

[[r2_buckets]]
binding = "CLIP_BUCKET"
bucket_name = "netclipboard"

[[durable_objects.bindings]]
name = "MAILBOX"
class_name = "MailboxDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MailboxDO"]
